services:
  sqlite:
    image: keinos/sqlite3
    container_name: sqlite
    stdin_open: true
    tty: true
    volumes:
      - db:/data/db
    networks:
      - app-network

  nlw-nodejs:
    build:
      context: .
    container_name: nlw-nodejs
    depends_on:
      - sqlite
    ports:
      - '3333:3333'
    environment:
      DATABASE_URL: "file:/usr/src/app/prisma/dev.db"
      PORT: 3333
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db: